//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nova.Dnug.Domain.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nova.Dnug.Domain.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilene
        ///Akron
        ///Albuquerque
        ///Alexandria
        ///Allentown
        ///Amarillo
        ///Anaheim
        ///Anchorage
        ///Ann Arbor
        ///Antioch
        ///Arlington
        ///Arvada
        ///Athens
        ///Atlanta
        ///Augusta
        ///Aurora
        ///Austin
        ///Bakersfield
        ///Baltimore
        ///Baton Rouge
        ///Beaumont
        ///Bellevue
        ///Berkeley
        ///Billings
        ///Birmingham
        ///Boise
        ///Boston
        ///Bridgeport
        ///Broken Arrow
        ///Brownsville
        ///Buffalo
        ///Burbank
        ///Cambridge
        ///Cape Coral
        ///Carlsbad
        ///Carrollton
        ///Cary
        ///Cedar Rapids
        ///Centennial
        ///Chandler
        ///Charleston
        ///Charlotte
        ///Chattanooga
        ///Chesapeake
        ///Chicago
        ///Chula Vista
        ///Cincinnati
        ///Clarksville
        ///Clearw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Computer Science - MSc
        ///Advanced Emergency Care - MSc
        ///Advanced Manufacturing Technologies with the AMRC - MSc(Res)
        ///Advanced Mechanical Engineering - MSc(Res)
        ///Advanced Metallurgy - MMet
        ///Advanced Nursing Studies - Cert/Dip/MMedSci
        ///Advanced Software Engineering - MSc(Eng)
        ///Advancing Practice (School of Nursing and Midwifery) - MMedSci
        ///Aegean Archaeology - MA
        ///Aerodynamics and Aerostructures - MSc(Res)
        ///Aerospace Materials - Msc(Eng)
        ///American History - MA
        ///Applied Professional Studies in Educati [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agriculture
        ///Anthropology
        ///Art and architecture
        ///Astronomy
        ///Biology
        ///Business
        ///Chemistry
        ///Civil engineering
        ///Computer science
        ///Economics
        ///Education
        ///Electrical engineering
        ///Ethnic studies
        ///Film studies
        ///Foreign languages and culture
        ///Geology
        ///Geography
        ///History
        ///Industrial engineering
        ///Law
        ///Linguistics
        ///Literature and rhetoric
        ///Mathematics
        ///Mechanical engineering 
        ///Music
        ///Philosophy
        ///Physics
        ///Political science
        ///Psychology
        ///Sociology.
        /// </summary>
        internal static string Faculties {
            get {
                return ResourceManager.GetString("Faculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jacob
        ///Ethan
        ///Michael
        ///Alexander
        ///William
        ///Joshua
        ///Daniel
        ///Jayden
        ///Noah
        ///Anthony
        ///Christopher
        ///Aiden
        ///Matthew
        ///David
        ///Andrew
        ///Joseph
        ///Logan
        ///James
        ///Ryan
        ///Benjamin
        ///Elijah
        ///Gabriel
        ///Christian
        ///Nathan
        ///Jackson
        ///Isabella
        ///Emma
        ///Olivia
        ///Sophia
        ///Ava
        ///Emily
        ///Madison
        ///Abigail
        ///Chloe 
        ///Mia
        ///Elizabeth
        ///Addison
        ///Alexis
        ///Ella
        ///Samantha
        ///Natalie
        ///Grace
        ///Lily
        ///Alyssa
        ///Ashley
        ///Sarah
        ///Taylor
        ///Hannah
        ///Brianna 
        ///Hailey
        ///John
        ///Samuel
        ///Tyler
        ///Dylan
        ///Jonathan
        ///Caleb
        ///Nicholas
        ///Gavin
        ///Mason
        ///Evan
        ///Landon
        ///Angel
        ///Brandon
        ///Lucas        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Forenames {
            get {
                return ResourceManager.GetString("Forenames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alabama
        ///Alaska
        ///American Samoa
        ///Arizona
        ///Arkansas
        ///California
        ///Colorado
        ///Connecticut
        ///Delaware
        ///District of Columbia
        ///Florida
        ///Georgia
        ///Guam
        ///Hawaii
        ///Idaho
        ///Illinois
        ///Indiana
        ///Iowa
        ///Kansas
        ///Kentucky
        ///Louisiana
        ///Maine
        ///Maryland
        ///Massachusetts
        ///Michigan
        ///Minnesota
        ///Mississippi
        ///Missouri
        ///Montana
        ///Nebraska
        ///Nevada
        ///New Hampshire
        ///New Jersey
        ///New Mexico
        ///New York
        ///North Carolina
        ///North Dakota
        ///Northern Marianas Islands 
        ///Ohio
        ///Oklahoma
        ///Oregon
        ///Pennsylvania
        ///Puerto Rico
        ///Rhode Island
        ///South Carolina
        ///South Dak [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbey Court
        ///Aberdeen Street
        ///Adams Street
        ///Adelphi Street
        ///Adler Place
        ///Agate Court
        ///Ainslie Street
        ///Aitken Place
        ///Alabama Avenue
        ///Albany Avenue
        ///Albee Square
        ///Albemarle Road
        ///Albemarle Terrace
        ///Alice Court
        ///Allen Avenue
        ///Alton Place
        ///Amber Street
        ///Amboy Street
        ///Amersfort Place
        ///Amherst Street
        ///Amity Street
        ///Anchorage Place
        ///Anna Court
        ///Anthony Street
        ///Apollo Street
        ///Applegate Court
        ///Argyle Road
        ///Arion Place
        ///Arkansas Drive
        ///Arlington Avenue
        ///Arlington Place
        ///Ash Street
        ///Ashford Street
        ///Ashland Place
        ///Aste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Streets {
            get {
                return ResourceManager.GetString("Streets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMITH
        ///JOHNSON
        ///WILLIAMS
        ///JONES
        ///BROWN
        ///DAVIS
        ///MILLER
        ///WILSON
        ///MOORE
        ///TAYLOR
        ///ANDERSON
        ///THOMAS
        ///JACKSON
        ///WHITE
        ///HARRIS
        ///MARTIN
        ///THOMPSON
        ///GARCIA
        ///MARTINEZ
        ///ROBINSON
        ///CLARK
        ///RODRIGUEZ
        ///LEWIS
        ///LEE
        ///WALKER
        ///HALL
        ///ALLEN
        ///YOUNG
        ///HERNANDEZ
        ///KING
        ///WRIGHT
        ///LOPEZ
        ///HILL
        ///SCOTT
        ///GREEN
        ///ADAMS
        ///BAKER
        ///GONZALEZ
        ///NELSON
        ///CARTER
        ///MITCHELL
        ///PEREZ
        ///ROBERTS
        ///TURNER
        ///PHILLIPS
        ///CAMPBELL
        ///PARKER
        ///EVANS
        ///EDWARDS
        ///COLLINS
        ///STEWART
        ///SANCHEZ
        ///MORRIS
        ///ROGERS
        ///REED
        ///COOK
        ///MORGAN
        ///BELL
        ///MURPHY
        ///BAILEY
        ///RIVERA
        ///COOPER
        ///RICHARDSON
        ///COX
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilene Christian University
        ///Abraham Baldwin Agricultural College
        ///Academy of Art College
        ///Academy of the New Church College
        ///Adams State College
        ///Adelphi University
        ///Adrian College
        ///Agnes Scott College
        ///AIB College of Business
        ///Air Force Institute of Technology
        ///Air University
        ///Alabama A&amp;M University
        ///Alabama State University
        ///Alamance College
        ///Alaska Bible College
        ///Alaska Pacific University
        ///Albany College of Pharmacy
        ///Albany State College
        ///Albany State University
        ///Albertson College of Idaho
        ///Albertus Ma [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Universities {
            get {
                return ResourceManager.GetString("Universities", resourceCulture);
            }
        }
    }
}
